'use client';

import { ArrowRight, Building2, CheckCircle2, Sparkles } from 'lucide-react';
import { motion } from 'framer-motion';
import FloatingObjects from '@/components/FloatingObjects';
import DashboardMock from '@/components/DashboardMock';
import ContactForm from '@/components/contact/ContactForm';
import { getCmsIcon } from '@/lib/icon-map';
import { activeSorted, type HomeContent } from '@/types/cms';

export default function HomePageClient({ content }: { content: HomeContent }) {
  const products = activeSorted(content.products.items);
  const capabilities = activeSorted(content.capabilities.items);
  return <main className="min-h-screen overflow-hidden">
    <section className="relative overflow-hidden px-5 pb-20 pt-6 md:pb-28">
      <div className="absolute inset-0" style={{ backgroundImage: `url('${content.hero.backgroundImage}')`, backgroundSize: 'cover', backgroundPosition: 'center top', backgroundRepeat: 'no-repeat' }} /><div className="absolute inset-0 bg-white/20" /><div className="absolute inset-0 bg-gradient-to-b from-sky-200/20 via-sky-100/10 to-white/40" /><div className="absolute bottom-0 left-0 h-40 w-full bg-gradient-to-t from-white to-transparent" />
      <FloatingObjects />
      <nav className="glass relative z-10 mx-auto flex max-w-7xl items-center justify-between rounded-full px-5 py-3"><div className="flex items-center gap-2 font-bold"><span className="grid h-9 w-9 place-items-center rounded-full bg-slate-950 text-white">{content.navigation.logoText}</span>{content.navigation.brandName}</div><div className="hidden items-center gap-8 text-sm font-medium text-slate-600 md:flex">{content.navigation.links.map((link) => <a key={link.href} href={link.href}>{link.label}</a>)}</div><a href={content.navigation.cta.href} className="rounded-full bg-slate-950 px-5 py-2.5 text-sm font-semibold text-white shadow-lg shadow-slate-900/20">{content.navigation.cta.label}</a></nav>
      <div className="relative z-10 mx-auto mt-20 max-w-7xl text-center"><motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="mx-auto mb-6 inline-flex items-center gap-2 rounded-full border border-blue-200 bg-white/70 px-4 py-2 text-sm font-medium text-blue-700 shadow-sm"><Sparkles className="h-4 w-4" /> {content.hero.badge}</motion.div><motion.h1 initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }} className="mx-auto max-w-5xl text-5xl font-bold tracking-tight text-slate-950 md:text-7xl">{content.hero.titlePrefix} <span className="gradient-text">{content.hero.titleHighlight}</span></motion.h1><motion.p initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }} className="mx-auto mt-6 max-w-3xl text-lg leading-8 text-slate-600">{content.hero.description}</motion.p><motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.3 }} className="mt-9 flex flex-col justify-center gap-4 sm:flex-row"><a href={content.hero.primaryCta.href} className="inline-flex items-center justify-center gap-2 rounded-full bg-blue-600 px-7 py-4 font-semibold text-white shadow-xl shadow-blue-500/20">{content.hero.primaryCta.label} <ArrowRight className="h-5 w-5" /></a><a href={content.hero.secondaryCta.href} className="inline-flex items-center justify-center rounded-full border border-slate-200 bg-white px-7 py-4 font-semibold text-slate-800 shadow-sm">{content.hero.secondaryCta.label}</a></motion.div></div>
      {content.dashboard.enabled && <div className="relative left-1/2 z-10 mt-6 w-screen -translate-x-1/2 md:mt-8"><DashboardMock values={content.dashboard} /></div>}
    </section>
    <section className="border-y border-slate-200 bg-white/60 py-5"><div className="animate-marquee flex w-[200%] gap-8 whitespace-nowrap text-sm font-semibold uppercase tracking-[0.2em] text-slate-400">{[...content.audiences, ...content.audiences, ...content.audiences].map((item, index) => <span key={`${item}-${index}`}>{item}</span>)}</div></section>
    <section id="products" className="mx-auto max-w-7xl px-5 py-24"><div className="mb-12 max-w-3xl"><p className="mb-3 font-semibold text-blue-600">{content.products.eyebrow}</p><h2 className="text-4xl font-bold tracking-tight text-slate-950 md:text-5xl">{content.products.heading}</h2></div><div className="grid gap-5 md:grid-cols-2">{products.map((service, index) => { const Icon = getCmsIcon(service.icon); return <motion.div key={service.key} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * 0.08 }} className="group rounded-[2rem] border border-slate-200 bg-white p-8 shadow-sm transition hover:-translate-y-1 hover:shadow-soft"><Icon className="mb-8 h-9 w-9 text-blue-600" /><h3 className="text-2xl font-bold text-slate-950">{service.title}</h3><p className="mt-4 leading-7 text-slate-600">{service.text}</p></motion.div>; })}</div></section>
    <section id="platform" className="bg-slate-950 px-5 py-24 text-white"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[0.8fr_1.2fr] lg:items-center"><div><p className="mb-3 font-semibold text-cyan-300">{content.platform.eyebrow}</p><h2 className="text-4xl font-bold tracking-tight md:text-5xl">{content.platform.heading}</h2><p className="mt-6 leading-8 text-slate-300">{content.platform.description}</p></div><div className="grid gap-4 sm:grid-cols-2">{content.platform.features.map((feature) => <div key={feature} className="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/[0.04] p-4"><CheckCircle2 className="h-5 w-5 text-cyan-300" /><span className="text-slate-200">{feature}</span></div>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-24"><div className="grid gap-5 md:grid-cols-3">{capabilities.map((item) => { const Icon = getCmsIcon(item.icon); return <div key={item.key} className="rounded-[2rem] bg-white p-8 shadow-sm ring-1 ring-slate-200"><Icon className="mb-8 h-8 w-8 text-blue-600" /><h3 className="text-xl font-bold">{item.title}</h3><p className="mt-4 leading-7 text-slate-600">{item.text}</p></div>; })}</div></section>
    <section id="pricing" className="mx-auto max-w-7xl px-5 pb-24"><div className="rounded-[2.5rem] bg-gradient-to-br from-blue-600 to-slate-950 p-8 text-white md:p-14"><div className="grid gap-10 lg:grid-cols-[1fr_0.8fr] lg:items-center"><div><Building2 className="mb-8 h-10 w-10 text-cyan-200" /><h2 className="text-4xl font-bold tracking-tight md:text-5xl">{content.pricing.heading}</h2><p className="mt-6 max-w-2xl leading-8 text-blue-100">{content.pricing.description}</p></div><div className="rounded-[2rem] bg-white p-6 text-slate-950 shadow-2xl"><p className="text-sm font-semibold text-blue-600">{content.pricing.cardLabel}</p><p className="mt-2 text-5xl font-bold">{content.pricing.priceText}</p><p className="mt-4 leading-7 text-slate-600">{content.pricing.cardDescription}</p><a href={content.pricing.cta.href} className="mt-8 inline-flex w-full items-center justify-center gap-2 rounded-full bg-slate-950 px-6 py-4 font-semibold text-white">{content.pricing.cta.label} <ArrowRight className="h-5 w-5" /></a></div></div></div></section>
    <footer id="contact" className="border-t border-slate-200 bg-white px-5 py-12"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-center"><div><h3 className="text-2xl font-bold">{content.footer.brandName}</h3><p className="mt-2 text-slate-600">{content.footer.description}</p></div><a href={`mailto:${content.footer.email}`} className="rounded-full bg-slate-950 px-6 py-3 font-semibold text-white">{content.footer.email}</a></div><ContactForm endpoint="/api/leads" /></div></footer>
  </main>;
}
